### ISSUE TITLE
Inf 服务器的功能需求

### ISSUE THREAD

**Issue by Acappellia** [NyaaCat/Saika#1]
### 铸造 / Forge

取消掉除boss掉落武器外的所有常规装备的常驻兑换途径，改为将它们添加到铸造池中。获取装备通过投入一定数量的晶石和铸造金属，来获取相应的装备，并带有随机性。对于重复/过时的装备，可以将他们分解来获得部分铸造金属。

为铸造池中每一件装备指定以下的参数：

**属性**，对应某一种属性的晶石。可以按照装备的类型（剑、弓、枪、法杖、防具……）对应到不同的属性。

**等级**，对应不同等级的铸造金属。

**最低铸造消耗**，得到该装备最少应投入的铸造金属个数。

**权重**，该装备在所有可能铸造出的装备中所占的权重比例，默认值等于最低铸造消耗。这是个整数。

玩家通过指令打开一个熔炉的铸造页面，在上栏放入一定数量的某等级的铸造金属，下一栏放入某个属性的一个晶石。右侧会出现一个代表铸造结果的物品。玩家点击右侧的物品时，会生成一个可能铸造结果的列表，每一项结果会带有各自的权重比例。玩家会在这个列表中，按照权重得到一个随机物品。

可能铸造结果列表按照以下规则生成：

根据投入的晶石属性，筛选出对应**属性**的物品；
根据投入的金属等级，筛选出对应**等级**的物品；
根据投入的金属数量，筛选出**最低铸造消耗**小于等于投入数量的物品；

在得到的列表中，对其中最低铸造消耗最高的物品的权重进行修改：

`新权重 = round ( 原权重 * 投入金属数量 / 最低铸造消耗 )`

最后，按照权重随机给玩家其中的一个物品。

每次铸造会消耗投入的全部铸造金属，和一定数量的晶石。1,2级铸造消耗1个晶石，3,4级铸造消耗2个晶石，5级铸造消耗3个晶石。该项数值可在配置文件中修改

如果投入的晶石数量不足，则返还全部材料，并提示晶石数量不足。
如果投入的铸造金属数量过少，导致可能的结果列表为空，则返还全部材料，并提示铸造金属不足。
如果投入材料有任何不符，则同样返还材料，并提示材料错误。

铸造和重铸可以有几率获得 bonus。

### 分解 / Recycle

同样，对于物品分解， 通过指令打开一个熔炉界面后，在上栏放入装备，下栏放入分解石，在结果栏返还该物品最低铸造消耗的一部分金属，不返还晶石。返还的比例可配置。 分解完成后消耗装备和一个分解石。

在分解时，需要对放入的物品进行识别。识别对象包括原版/RGI物品。如果识别到的物品不存在于铸造池，则提示错误，不消耗物品。

### 附魔 / 消魔

使用 GUI 界面来替代 NyaaUtils 的高等附魔功能，并提供消魔。

**附魔源**，名称和 lore 匹配的附魔书物品。

使用时，通过命令打开熔炉界面。下方放入附魔源，上面放入目标物品。在结果栏返还添加对应源上所有附魔和一部分等级的物品并消耗附魔源。

**消魔源**，NBT 严格匹配的消耗性材料。

使用时，通过命令打开熔炉界面，下方放入消魔源，上面放入物品。随机清除该物品的一项附魔后返还物品和一些经验值。

| 命令 | 权限 | 描述 |
| --- | --- | --- |
| `/saika open forge` | `saika.open.forge` | 打开铸造/分解 UI 页面 |
| `/saika open enchant` | `saika.open.enchant` | 打开附魔/消魔 UI 页面 |
| `/saika reload` | `saika.admin.reload` | 重新读取配置文件 |
| `/saika define level <level> <element-consumption>` | `saika.admin.define` | 定义手中的物品为某一等级的铸造金属 |
| `/saika define element <element>` | `saika.admin.define` | 定义手中的物品为某个属性的晶石 |
| `/saika define recycle` | `saika.admin.define` | 定义手中的物品分解石 |
| `/saika define enchant` | `saika.admin.define` | 定义手中的附魔书物品的名称和 lore 为附魔源 |
| `/saika define repulse` | `saika.admin.define` | 定义手中的附魔书物品的名称和 lore 为消魔源 |
| `/saika delete [level\|element\|recycle\|enchant\|repulse] <id>` | `saika.admin.delete` | 删除特定的金属/晶石/附魔/etc... |
| `/saika add <level> <element> <consumption> [weight]` | `saika.admin.add` | 将手中的物品添加到铸造池，并为这个物品添加一个铸造ID，返回这个铸造ID |
| `/saika remove <id>` | `saika.admin.remove` | 删除某个 ID 物品 |
| `/saika modify <id> [level\|element\|consumption\|weight\|recycle] <value>` | `saika.admin.modify` | 修改某个铸造的属性值。|
| `/saika bonus add` | `saika.admin.bonus` | 将手中的物品添加为 bonus 物品，返回 `bonus id` |
| `/saika bonus set [forge\|recycle] <forge id> <bonus id> <probability>` | `saika.admin.bonus` | 设置某个物品铸造或重铸的奖励。|
| `/saika inspect <id>` | `saika.admin.inspect` | 查看某个铸造 |
| `/saika list level:<level> element:<element>` | `saika.list` | 列出符合等级和属性的所有结果，显示结果包含了这个物品的所有参数 |

**Comment by phoenixlzx** [comment]
一些配置文件的示例

`config.yml`

```
language: en_US # use en_US.yml
forge:
  roll:
    maxWeightMultiplier: 3
enchant:
  exp: 200 # 附魔每等级消耗玩家 200 点经验，玩家经验不足时拒绝附魔
  maxLevel: 10
  probability:
    success: 40
    moderate: 50
    fail: 9
    destroy: 1
repulse:
  exp: 100 # 消除的附魔每等级在玩家身上生成共计 100 点的经验球，最多不超过 20 个经验球
  blacklist:
  - VANISHING_CURSE # 此附魔不会被消魔掉
sound:
  forge:
    name: minecraft:block.anvil.use
    pitch: 1.5
  recycle:
    name: minecraft:block.anvil.use
    pitch: 0.5
  success:
    name: minecraft:block.enchantment_table.use
    pitch: 1.5
  fail:
    name: minecraft:block.enchantment_table.use
    pitch: 0.5
effect:
  forge:
    particle: portal
    offsetX: 0
    offsetY: 1
    offsetZ: 0
    speed: 0
    amount: 100
    extra: ''
  recycle:
    particle: flame
    offsetX: 0
    offsetY: 1
    offsetZ: 0
    speed 0.1
    amount: 100
    extra: ''
  success:
    particle: enchant
    offsetX: 0
    offsetY: 1
    offsetZ: 0
    speed: 0.1
    amount: 100
    extra: ''
  fail:
    particle: slime
    offsetX: 0
    offsetY: 1
    offsetZ: 0
    speed: 0.1
    amount: 100
    extra: ''
position:
  forge:
    block: crafting_table
    distance: 3 # 必须在合成台为中心 7x7x7 方块范围内才能打开界面
  enchant:
    block: enchanting_table
    distance: 3
```

`level.yml`

```
level:
  '1':
    element: 1 # 该等级对应消耗的 element 数量
    nbt: <item nbt data> # 物品 NBT
  '2': 
    element: 2
    nbt: <item nbt data>
```

`element.yml`

```
element:
  'light':
    nbt: <item nbt data>
  'dark':
    nbt: <item nbt data>
```

`recycle.yml`

```
recycle:
  '1': <item nbt>
```

`enchant.yml`

```
enchant:
  '1':
    itemTemplate:   
      ==: org.bukkit.inventory.ItemStack
      v: 1631
      type: ENCHANTED_BOOK
      meta:
        ==: ItemMeta
        meta-type: ENCHANTED
        display-name: §eBook of Enchanting
        lore:
        - §dUsed to Enchant
        stored-enchants:
          LOOT_BONUS_BLOCKS: 1
    requireExact: false
    minDamageValue: -2
    maxDamageValue: -2
    enchantMatch: ARBITRARY
    loreMatch: EXACT_TEXT
    nameMatch: EXACT
    repairCostMatch: EXACT
```

`repulse.yml`

```
repulse:
  '1':
    nbt: <item nbt>
```

目录 `bonus` 保存所有 bonus 物品

`bonus/<bonus-id>.yml`

```
id: <bonus-id>
nbt: <item nbt data>
```

目录 `items` 保存所有输出物品

`items/<forge-id>.yml`

```
id: <forge-id>
nbt: <item nbt data> # 铸造结果物品 nbt
recycle: # 返还 10%~30% 最低需求的铸造金属，至少会返还 1 个。
  min: 10
  max: 30
  hard: 1
  bonus:
    item: <bonus-id>
    chance: 50 # 50% 几率分解物品获得此 bonus
forge:
  level: '1'
  element: 'dark'
  consumption: 3
  weight: 1
  bonus:
    item: '' # 默认值没有 bonus
    chance: 0
```

铸造/附魔等界面逻辑实现参考 ce 的 runecraft
